Actions, tests, oh my
* Remove Travis from readme
* Update build status images
* Add smoke tests and mock data
* Enable dot env on Serverless

diff --git a/.github/workflows/dev.yml b/.github/workflows/dev.yml
--- a/.github/workflows/dev.yml
+++ b/.github/workflows/dev.yml
@@ -1,13 +1,21 @@
 # Docs:
 # https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions
 
-name: build-alexa-icestatus-dev
+name: Build Develop
 
 on:
   push:
     branches: [ develop ]
+    paths:
+      - '**.js'
+      - '**.yml'
+      - 'test/**'
   pull_request:
     branches: [ develop ]
+      paths:
+      - '**.js'
+      - '**.yml'
+      - 'test/**'
 
 defaults:
   run:
@@ -43,3 +51,11 @@ jobs:
 
       - name: Deploy with Serverless
         run: serverless deploy -s $SLS_STAGE
+
+      # - name: Smoke testing the deployment
+      #   if: ${{ success() }}
+      #   run: |
+      #     sh tests/run-tests.sh
+      #     if [[ $? != 0 ]]; then
+      #       echo "Failed smoke tests, rolling back"
+      #     fi
